version: "3.3"

services:
  ai-dump:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - target: 80
       published: 8080
       protocol: tcp
       mode: host
    links:
      - fpm
  fpm:
    image: php:7-fpm
    expose:
        - 9000
    volumes:
        - ./src:/usr/share/nginx/html
